# -*- coding: utf-8 -*-
"""student-grade-calculator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10AYoYmUcfAQIEk5ZvPSuiY0PXwSH4Y53

# **CI using Github Actions**

**Student Grade Calculator**
"""

def calculate_average(marks):
    return sum(marks) / len(marks)


def calculate_grade(average):
    if average >= 90:
        return "A+"
    elif average >= 75:
        return "A"
    elif average >= 60:
        return "B"
    elif average >= 50:
        return "C"
    else:
        return "Fail"


def main():
    marks = []
    print("This is a program to Determine the grade")
    print("There are 5 subjects and maximum marks per subject is 100")

    for i in range(1, 6):
        mark = float(input(f"Enter marks for subject {i}: "))
        marks.append(mark)

    average = calculate_average(marks)
    grade = calculate_grade(average)

    print("\nAverage Marks:", average)
    print("Grade:", grade)


if __name__ == "__main__":
    main()