# -*- coding: utf-8 -*-
"""test_grade_calculator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vcXjWoAq9OAqfu0iaS3pc2Me_LiTLNaJ
"""

from grade_calculator import calculate_average, calculate_grade


def test_average_calculation():
    marks = [80, 90, 70, 60, 100]
    assert calculate_average(marks) == 80


def test_grade_A_plus():
    assert calculate_grade(95) == "A+"


def test_grade_A():
    assert calculate_grade(80) == "A"


def test_grade_B():
    assert calculate_grade(65) == "B"


def test_grade_C():
    assert calculate_grade(55) == "C"


def test_grade_fail():
    assert calculate_grade(40) == "Fail"